mod 'puppetlabs/stdlib'
mod 'herculesteam/augeasproviders_core'
mod 'herculesteam/augeasproviders_sysctl'
mod 'saz/ssh'
mod 'puppetlabs/concat'
mod 'puppetlabs/translate'
mod 'puppetlabs-accounts', '6.1.0'
mod 'hardening-ssh_hardening', '1.0.5'
mod 'hardening-os_hardening', '2.2.7'
